feat: db migration lib

diff --git a/core/makefile b/core/makefile
--- a/core/makefile
+++ b/core/makefile
@@ -19,3 +19,13 @@ lint:
 .PHONY: bundle build
 bundle build:
 	poetry run pyinstaller -y --clean ai-assistant-core.spec
+
+
+# Usage: `make add-migration m="YOUR MIGRATION NAME"`
+.PHONY: add-migration
+add-migration:
+	@if [ -z "$(m)" ]; then \
+		echo "Error: Missing migration name. Use 'make add-migration m=\"YOUR MIGRATION NAME\"'"; \
+		exit 1; \
+	fi
+	@cd ./ai_assistant_core/infrastructure && poetry run alembic revision -m "$(m)"
